### ISSUE TITLE
JavaScript Error "h is null" when running certain tests

### ISSUE THREAD

**Issue by danascheider** [danascheider/canto-front-end#26]
A couple of times now, I have had very cryptic error messages appear when running RSpec tests with Selenium. I don't remember how I solved this last time (though I do remember the solution was not elegant), and now I'm seeing it again. 

I have these tests for the core dashboard elements:
<pre><code>describe 'core dashboard elements' do 
  before(:all) do 
    DRIVER.manage.add_cookie(name: 'auth', value: Base64.encode64('testuser:testuser').gsub(/\=/, '%3D'))
    DRIVER.manage.add_cookie(name: 'userID', value: '342')
  end

  before(:each) do 
    DRIVER.get "#{BASEPATH}/#dashboard"
  end

  describe 'visible elements' do 
    it 'has a top nav element' do 
      expect(DRIVER.find_element(:class_name, 'navbar-fixed-top')).to be_displayed
    end

    it 'has a side nav element' do 
      expect(DRIVER.find_element(:class_name, 'navbar-static-side')).to be_displayed
    end
  end
end</pre></code>
When I run the tests, both fail with the same error message:
<pre><code>Failure/Error: expect(DRIVER.find_element(:class_name, 'navbar-static-side')).to be_displayed
     Selenium::WebDriver::Error::UnknownError:
       [JavaScript Error: "h is null" {file: "file:///tmp/webdriver-profile20150103-7358-bo8bp5/extensions/fxdriver@googlecode.com/components/command-processor.js" line: 7886}]'[JavaScript Error: "h is null" {file: "file:///tmp/webdriver-profile20150103-7358-bo8bp5/extensions/fxdriver@googlecode.com/components/command-processor.js" line: 7886}]' when calling method: [nsICommandProcessor::execute]
     # /home/dana/.rvm/gems/ruby-2.1.3/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/response.rb:52:in `assert_ok'
     # /home/dana/.rvm/gems/ruby-2.1.3/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/response.rb:15:in `initialize'
     # /home/dana/.rvm/gems/ruby-2.1.3/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/common.rb:59:in `new'
     # /home/dana/.rvm/gems/ruby-2.1.3/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/common.rb:59:in `create_response'
     # /home/dana/.rvm/gems/ruby-2.1.3/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/default.rb:66:in `request'
     # /home/dana/.rvm/gems/ruby-2.1.3/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/http/common.rb:40:in `call'
     # /home/dana/.rvm/gems/ruby-2.1.3/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:640:in `raw_execute'
     # /home/dana/.rvm/gems/ruby-2.1.3/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:618:in `execute'
     # /home/dana/.rvm/gems/ruby-2.1.3/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/remote/bridge.rb:586:in `find_element_by'
     # /home/dana/.rvm/gems/ruby-2.1.3/gems/selenium-webdriver-2.44.0/lib/selenium/webdriver/common/search_context.rb:42:in `find_element'
     # ./spec/dashboard_spec.rb:19:in `block (3 levels) in &lt;top (required)&gt;'</code></pre>
I'll be sure to document how I get this resolved this time.

**Comment by danascheider** [comment]
It is worth mentioning that, as of October 2014, this was a [documented issue with Selenium](https://code.google.com/p/selenium/issues/detail?id=7977) that continued to be an issue despite being "fixed".

**Comment by danascheider** [comment]
For the time being, this issue has disappeared on its own - without further changes to the test suite. I am wrapping it into the larger issue - #27 (which I am about to open), dealing with flickering tests.
